Moving rbenv install to bin/setup + .travis.yml

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -10,11 +10,9 @@
 #       https://github.com/kigster/bashmatic
 #
 # The framework is pretty light-weight, and is installed in your $HOME/.bashmatic folder.
-# You can safely remove that folder after the setup if you wish, although re-running the 
+# You can safely remove that folder after the setup if you wish, although re-running the
 # setup will re-install it.
 # —————————————————————————————————————————————————————————————————————————————————————
-
-set -e
 
 source "bin/deps"
 
@@ -30,6 +28,59 @@ __setup.actions() {
 #—————————————————————————————————————————————————————————————————————————————————————————————————————————————
 # Public Functions
 #—————————————————————————————————————————————————————————————————————————————————————————————————————————————
+
+setup.rbenv() {
+  local rbenv_home="${HOME}/.rbenv"
+  local ruby_version="$(cat .ruby-version | tr -d '\n')"
+
+  if [[ -n $(command -v ruby) ]]; then
+    local installed_version="$(ruby -e 'puts RUBY_VERSION' | tr -d '\n')"
+    if [[ ${installed_version} == ${ruby_version} ]]; then
+      info "RUBY already installed, current version: ${bldylw}${ruby_version}"
+      return 0
+    fi
+  fi
+
+  [[ -d "${rbenv_home}" && -f "${rbenv_home}/bin/rbenv" ]] || {
+    if [[ -z ${CI} ]]; then
+      warning "You are on a local system without any RBENV..."
+      run.ui.ask "Are you sure you want to wipe your local ~/.rbenv?"
+    fi
+
+    warning "Recreating RBENV home, downloading rbenv..."
+    run "rm -rf ${rbenv_home}"
+    run "git clone https://github.com/rbenv/rbenv.git ${rbenv_home}"
+    export PATH="${rbenv_home}/bin:${rbenv_home}/shims:${PATH}"
+  }
+
+  export PATH="${rbenv_home}/bin:${rbenv_home}/shims:${PATH}"
+
+  [[ $(which rbenv) == "${rbenv_home}/bin/rbenv" ]] || {
+    error "Can't find rbenv in the PATH — which rbenv returns: $(which rbenv)"
+    error "PATH: ${PATH}"
+    return 1
+  }
+
+  # Set our current ruby version to the desired one, even if it's not yet there.
+  # This allows the next block to auto-detect it and skip the remainder.
+  run "rbenv global ${ruby_version} || true"
+  # see if we even need to install anything:
+  local ruby_sdk_marker="$(rbenv versions | grep "${ruby_version}" | cut -d ' ' -f 1)"
+  if [[ ${ruby_sdk_marker} == "*" ]]; then
+    info "Ruby Version ${ruby_version} is already present, and is RBENV default."
+    info "Skipping the rest of RBENV setup."
+    return 0
+  fi
+
+  eval "$(rbenv init -)"
+  run "mkdir -p ${rbenv_home}/plugins"
+  run "git clone https://github.com/rbenv/ruby-build.git ${rbenv_home}/plugins/ruby-build"
+  run "rbenv rehash"
+  hash -r
+
+  run "rbenv install -s ${ruby_version}"
+  run "rbenv global ${ruby_version}"
+}
 
 setup.gems() {
   for gem in rubocop relaxed-rubocop; do
@@ -70,7 +121,7 @@ setup.os-specific() {
     eval "setup.${os} \"$*\""
     echo
     if [[ -z ${CI} ]]; then
-      info "Please note — to print your Bazel environment run " 
+      info "Please note — to print your Bazel environment run "
       info "❯ ${bldylw}bin/show-env"
     else
       /usr/bin/env bash bin/show-env || true
@@ -88,8 +139,11 @@ setup.main() {
   local is_help=0
   local code=0
 
-  [[ "${action}" == "-h" || ${action} == "--help" ]] && { action="help"; is_help=1; }
-  
+  [[ "${action}" == "-h" || ${action} == "--help" ]] && {
+    action="help"
+    is_help=1
+  }
+
   local func="setup.${action}"
 
   if [[ -n ${action} ]]; then
@@ -98,12 +152,12 @@ setup.main() {
       shift
       ${func} "$@"
       code=$?
-      [[ ${code} -eq 0 ]] && { 
+      [[ ${code} -eq 0 ]] && {
         ((is_help)) || success "Setup for ${action} was successful"
       }
       [[ ${code} -ne 0 ]] && error "Error setting up ${action}"
     else
-      error "Invalid action provided — '${action}'" 
+      error "Invalid action provided — '${action}'"
       info "Valid actions are: [ ${bldylw}${action_list}$(txt-info) ]"
       echo
       code=1
@@ -111,6 +165,7 @@ setup.main() {
   else
     set +e
     h2 "Installing required development dependencies for working with rules_ruby and Bazel."
+    setup.rbenv
     setup.gems
     [[ -z ${CI} ]] && setup.git-hook
     setup.os-specific "$@"
@@ -155,4 +210,4 @@ $(help-example "bin/setup remove-git-hook")
 action_list="$(__setup.actions " | " | sed 's/setup\.//g')"
 export action_list
 
-setup.main "$@"
+bashmatic.detect-subshell || setup.main "$@"
