Sight facelift to shell files:
 This is mostly a collection of various stashes combined together.

 * making setup-linux a bit less unsafe
 * adding a diagram
 * printing all sorts of veresions in the bin/setup
 * making **gemfile** mandatory for `bundle_install`.

diff --git a/bin/setup-linux b/bin/setup-linux
--- a/bin/setup-linux
+++ b/bin/setup-linux
@@ -7,9 +7,22 @@
   exit 1
 }
 
+function setup::linux::deps() {
+  if [[ -z $(command -v apt-get) ]]; then
+    [[ -n $(command -v curl) && -n $(command -v wget) ]] && return 0
+  else
+    error "Unable to find the right packaging tool to install dependencies."
+    exit 1
+  fi
+
+  [[ -n $(command -v curl) && -n $(command -v wget) ]] || {
+    error "curl and wget must be pre-installed."
+    exit 2
+  }
+}
+
 function setup::linux() {
-  local version
-  version="${1}"
+  local version="${1}"
 
   [[ -z "${version}" && -f .bazelversion ]] && version=$(cat .bazelversion | tr -d '\n')
 
@@ -20,25 +33,31 @@ function setup::linux() {
     hl::subtle "Installing Bazel version ${version}"
   fi
 
-  local installer=bazel-${version}-installer-linux-x86_64.sh
-  local release_base_uri=https://github.com/bazelbuild/bazel/releases/download/${version}
+  # Ensure we have the tools like curl and wget installed
+  setup::linux::deps
+
+  local installer="bazel-${version}-installer-linux-x86_64.sh"
+  local release_base_uri="https://github.com/bazelbuild/bazel/releases/download/${version}"
   local require_install=true
-  if test -x ${HOME}/local/${installer}; then
-    cd ${HOME}/local
-    if curl ${release_base_uri}/${installer}.sha256 | sha256sum -c; then
+
+  local installer_path="${HOME}/.ruby_local"
+  local installer_exe="${installer_path}/${installer_exe}"
+
+  if [[ -x "${installer_exe}" ]]; then
+    if curl "${release_base_uri}/${installer}.sha256" | sha256sum -c; then
       require_install=false
     fi
   fi
 
   if ${require_install}; then
-    run "rm -rf ${HOME}/local"
-    run "mkdir ${HOME}/local"
-    run "cd ${HOME}/local"
+    run "rm -rf ${installer_path}"
+    run "mkdir -p ${installer_path}"
+    run "cd ${installer_path}"
     run "wget ${release_base_uri}/${installer}"
     run "chmod +x ${installer}"
 
     run::set-next show-output-on
-    run "./${installer} --prefix=${HOME}/local --base=${HOME}/.bazel"
+    run "./${installer_exe} --prefix=${installer_path} --base=${HOME}/.bazel"
   fi
 }
 
