Upgrade Bazel version to 1.2.1 + use bin/setup(s) (#31)
* instead of .travis/install-bazel.sh use bin/setup-linux
 * checkin ~/.bazelversion file used by bazelisk on OS-X
 * split up Darwin and Linux installers, but reuse what's common
 * updated .travis.yml

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -7,11 +7,44 @@
   exit 1
 }
 
-# abort on error
-run::set-all abort-on-error
+function setup::gem::dependencies() {
+  # abort on error
+  run::set-all abort-on-error
 
-lib::gem::cache-refresh
-lib::gem::install rubocop
-lib::gem::install relaxed-rubocop
+  lib::gem::cache-refresh
+  lib::gem::install rubocop
+  lib::gem::install relaxed-rubocop
+}
 
-[[ -L .git/hooks/pre-commit ]] || run "ln -nfs bin/pre-commit .git/hooks/pre-commit"
+function setup::git::commit-hook() {
+  [[ -L .git/hooks/pre-commit ]] || run "ln -nfs bin/pre-commit .git/hooks/pre-commit"
+}
+
+function setup::detect-bazel-version() {
+  local version
+  version="$(grep versions.check WORKSPACE | awk 'BEGIN{FS="\""}{print $2}')"
+  [[ -z "${version}" && -f .bazelversion ]] && version="$(cat .bazelversion | tr -d '\n')"
+  printf "%s" "${version}"
+}
+
+#——————————————————————————————  main ———————————————————————————————————————————
+
+function setup::main() {
+  setup::gem::dependencies
+  [[ -z ${CI} ]] && setup::git::commit-hook
+
+  local os=$(uname -s | tr '[:upper:]' '[:lower:]')
+  local script
+
+  script="./bin/setup-${os}"
+
+  if [[ -x ${script} ]]; then
+    "${script}" "$(setup::detect-bazel-version)"
+  else
+    echo "Operating system $(uname -s) is not currently supported." >&2
+    return 1
+  fi
+}
+
+setup::main "$@"
+
